CREATE TABLE USUARIO 
(
  CPF VARCHAR2(14) NOT NULL 
, NOME VARCHAR2(200) NOT NULL 
, EMAIL VARCHAR2(200) NOT NULL 
, SENHA VARCHAR2(200) NOT NULL 
, CONSTRAINT USUARIO_PK PRIMARY KEY 
  (
    CPF 
  )
  ENABLE 
);

CREATE TABLE VEICULO 
(
  PLACA VARCHAR2(10) NOT NULL 
, MODELO VARCHAR2(200) NOT NULL 
, ANO NUMBER NOT NULL 
, COR VARCHAR2(200) NOT NULL
, FABRICANTE VARCHAR2(200) NOT NULL
, CONSTRAINT VEICULO_PK PRIMARY KEY 
  (
    PLACA 
  )
  ENABLE 
);

CREATE TABLE PECA 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR2(200) NOT NULL 
, FABRICANTE VARCHAR2(200) NOT NULL 
, VALOR NUMBER NOT NULL 
, ID_VEICULO VARCHAR2(10) NOT NULL 
, CONSTRAINT PECA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE ENTRADA 
(
  ID NUMBER NOT NULL 
, DATA DATE NOT NULL 
, NOME_CLIENTE VARCHAR2(200) NOT NULL 
, TEL_CLIENTE VARCHAR2(20) NOT NULL 
, ID_VEICULO VARCHAR2(10) NOT NULL 
, ID_USUARIO VARCHAR2(14) NOT NULL 
, CONSTRAINT ENTRADA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE ENTRADA ADD CONSTRAINT FK_VEICULO
  FOREIGN KEY(ID_VEICULO) REFERENCES
  VEICULO(PLACA);

  ALTER TABLE ENTRADA ADD CONSTRAINT FK_USUARIO
  FOREIGN KEY(ID_USUARIO) REFERENCES
  USUARIO(CPF);
  
ALTER TABLE PECA ADD CONSTRAINT FK_VEICULO_PECA
  FOREIGN KEY(ID_VEICULO) REFERENCES
  VEICULO(PLACA);
  
CREATE SEQUENCE S_PECA INCREMENT BY 1 START WITH 1 MAXVALUE 99999 MINVALUE 1;
CREATE SEQUENCE S_ENTRADA INCREMENT BY 1 START WITH 1 MAXVALUE 99999 MINVALUE 1;
